global:
  scrape_interval: 15s # How frequently to scrape targets (default is 1m).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus monitoring itself

  - job_name: 'service-registry'
    metrics_path: '/actuator/prometheus' # The path for Micrometer metrics
    static_configs:
      - targets: ['localhost:8761'] # *** IMPORTANT: REPLACE WITH YOUR SPRING BOOT HOST'S IP and PORT ***
        labels:
          application: service-registry
    basic_auth:
      username: 'admin' # *** IMPORTANT: REPLACE WITH YOUR EUREKA_ADMIN_USER ***
      password: 'admin123' # *** IMPORTANT: REPLACE WITH YOUR EUREKA_ADMIN_PASS ***